"""baseline schema

Revision ID: ade7d99e9212
Revises: 
Create Date: 2026-06-10 21:19:59.202266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade7d99e9212'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('hostname', sa.String(length=80), nullable=True),
    sa.Column('ip', sa.String(length=40), nullable=True),
    sa.Column('mac', sa.String(length=20), nullable=True),
    sa.Column('service_tag', sa.String(length=40), nullable=True),
    sa.Column('os', sa.String(length=80), nullable=True),
    sa.Column('fabricante', sa.String(length=60), nullable=True),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('patrimonio', sa.String(length=40), nullable=True),
    sa.Column('nf', sa.String(length=40), nullable=True),
    sa.Column('categoria', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('colaborador', sa.String(length=120), nullable=True),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('unidade', sa.String(length=80), nullable=True),
    sa.Column('garantia', sa.String(length=10), nullable=True),
    sa.Column('criado_em', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_colaborador'), ['colaborador'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=16), nullable=False),
    sa.Column('original_name', sa.String(length=180), nullable=False),
    sa.Column('stored_name', sa.String(length=220), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=80), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_entity_type'), ['entity_type'], unique=False)

    op.create_table('audit_campaigns',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('unidade', sa.String(length=80), nullable=True),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_inicio', sa.String(length=10), nullable=True),
    sa.Column('data_fim', sa.String(length=10), nullable=True),
    sa.Column('criado_por', sa.String(length=80), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=True),
    sa.Column('modulo', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.String(length=120), nullable=True),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ref_id'), ['ref_id'], unique=False)

    op.create_table('colaboradores',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('unidade', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('matricula', sa.String(length=40), nullable=True),
    sa.Column('data_admissao', sa.String(length=10), nullable=True),
    sa.Column('data_cadastro', sa.String(length=10), nullable=True),
    sa.Column('data_desligamento', sa.String(length=10), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colaboradores_nome'), ['nome'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.String(length=16), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_ref_id'), ['ref_id'], unique=False)

    op.create_table('licenses',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('software', sa.String(length=120), nullable=True),
    sa.Column('fornecedor', sa.String(length=80), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('atribuidas', sa.Integer(), nullable=True),
    sa.Column('vencimento', sa.String(length=10), nullable=True),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_ip'), ['ip'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('supplies',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=True),
    sa.Column('unidade', sa.String(length=80), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('minimo', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_movements',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.String(length=16), nullable=True),
    sa.Column('supply_nome', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('colaborador', sa.String(length=120), nullable=True),
    sa.Column('ativo_id', sa.String(length=16), nullable=True),
    sa.Column('motivo', sa.String(length=80), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supply_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_movements_colaborador'), ['colaborador'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_movements_ref_id'), ['ref_id'], unique=False)

    op.create_table('system_users',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('senha_hash', sa.String(length=256), nullable=True),
    sa.Column('perfil', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('termos_avulsos',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('colaborador', sa.String(length=120), nullable=True),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('unidade', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('validade', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sign_token', sa.String(length=64), nullable=True),
    sa.Column('sign_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('assinatura_img', sa.Text(), nullable=True),
    sa.Column('assinatura_ip', sa.String(length=50), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sign_token')
    )
    op.create_table('allocations',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('ativo_id', sa.String(length=16), nullable=True),
    sa.Column('ativo_nome', sa.String(length=200), nullable=True),
    sa.Column('colaborador', sa.String(length=120), nullable=True),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('unidade', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('data_aloc', sa.String(length=10), nullable=True),
    sa.Column('data_encerramento', sa.String(length=10), nullable=True),
    sa.Column('motivo', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('termo', sa.String(length=30), nullable=True),
    sa.Column('termo_status', sa.String(length=20), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.Column('assinatura_ip', sa.String(length=50), nullable=True),
    sa.Column('assinatura_img', sa.Text(), nullable=True),
    sa.Column('sign_token', sa.String(length=64), nullable=True),
    sa.Column('sign_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('assinatura_ti_img', sa.Text(), nullable=True),
    sa.Column('assinatura_ti_nome', sa.String(length=120), nullable=True),
    sa.Column('data_assinatura_ti', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('data_devolucao_prevista', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sign_token')
    )
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocations_ativo_id'), ['ativo_id'], unique=False)

    op.create_table('audit_campaign_items',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('campaign_id', sa.String(length=16), nullable=False),
    sa.Column('asset_id', sa.String(length=16), nullable=True),
    sa.Column('asset_nome', sa.String(length=200), nullable=True),
    sa.Column('patrimonio', sa.String(length=40), nullable=True),
    sa.Column('service_tag', sa.String(length=40), nullable=True),
    sa.Column('expected_unidade', sa.String(length=80), nullable=True),
    sa.Column('expected_setor', sa.String(length=80), nullable=True),
    sa.Column('expected_colaborador', sa.String(length=120), nullable=True),
    sa.Column('observed_unidade', sa.String(length=80), nullable=True),
    sa.Column('observed_setor', sa.String(length=80), nullable=True),
    sa.Column('observed_local', sa.String(length=120), nullable=True),
    sa.Column('observed_responsavel', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('divergencia', sa.Text(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('auditado_por', sa.String(length=80), nullable=True),
    sa.Column('auditado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['audit_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devolucoes',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('colaborador_id', sa.String(length=16), nullable=True),
    sa.Column('colaborador', sa.String(length=120), nullable=False),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('unidade', sa.String(length=80), nullable=True),
    sa.Column('data_devolucao', sa.String(length=10), nullable=True),
    sa.Column('sign_token', sa.String(length=64), nullable=True),
    sa.Column('sign_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('assinatura_img', sa.Text(), nullable=True),
    sa.Column('assinatura_ip', sa.String(length=50), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ativos_devolvidos', sa.Text(), nullable=True),
    sa.Column('perifericos_devolvidos', sa.Text(), nullable=True),
    sa.Column('laudo_status', sa.String(length=30), nullable=True),
    sa.Column('rh_token', sa.String(length=64), nullable=True),
    sa.Column('rh_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('rh_email', sa.String(length=120), nullable=True),
    sa.Column('rh_ciencia_ip', sa.String(length=50), nullable=True),
    sa.Column('rh_data_ciencia', sa.DateTime(), nullable=True),
    sa.Column('cobranca_valor', sa.Float(), nullable=True),
    sa.Column('cobranca_obs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rh_token'),
    sa.UniqueConstraint('sign_token')
    )
    with op.batch_alter_table('devolucoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devolucoes_laudo_status'), ['laudo_status'], unique=False)

    op.create_table('maintenance_orders',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('asset_id', sa.String(length=16), nullable=True),
    sa.Column('asset_nome', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('descricao_defeito', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('tecnico', sa.String(length=120), nullable=True),
    sa.Column('data_abertura', sa.String(length=10), nullable=True),
    sa.Column('data_conclusao', sa.String(length=10), nullable=True),
    sa.Column('custo_total', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocation_items',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('allocation_id', sa.String(length=16), nullable=True),
    sa.Column('supply_id', sa.String(length=16), nullable=True),
    sa.Column('supply_nome', sa.String(length=120), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laudos_tecnicos',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('devolucao_id', sa.String(length=16), nullable=False),
    sa.Column('tecnico', sa.String(length=120), nullable=False),
    sa.Column('avaliacao_itens', sa.Text(), nullable=True),
    sa.Column('observacao_geral', sa.Text(), nullable=True),
    sa.Column('tem_cobranca', sa.Boolean(), nullable=True),
    sa.Column('valor_cobranca', sa.Float(), nullable=True),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=True),
    sa.Column('editado_em', sa.DateTime(), nullable=True),
    sa.Column('editado_por', sa.String(length=120), nullable=True),
    sa.Column('motivo_edicao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['devolucao_id'], ['devolucoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_parts',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('maintenance_id', sa.String(length=16), nullable=True),
    sa.Column('supply_id', sa.String(length=16), nullable=True),
    sa.Column('supply_nome', sa.String(length=120), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_parts')
    op.drop_table('laudos_tecnicos')
    op.drop_table('allocation_items')
    op.drop_table('maintenance_orders')
    with op.batch_alter_table('devolucoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devolucoes_laudo_status'))

    op.drop_table('devolucoes')
    op.drop_table('audit_campaign_items')
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocations_ativo_id'))

    op.drop_table('allocations')
    op.drop_table('termos_avulsos')
    op.drop_table('system_users')
    with op.batch_alter_table('supply_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_movements_ref_id'))
        batch_op.drop_index(batch_op.f('ix_supply_movements_colaborador'))

    op.drop_table('supply_movements')
    op.drop_table('supplies')
    op.drop_table('settings')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip'))

    op.drop_table('login_attempts')
    op.drop_table('licenses')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_ref_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colaboradores_nome'))

    op.drop_table('colaboradores')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_ref_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_data'))

    op.drop_table('audit_logs')
    op.drop_table('audit_campaigns')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_entity_type'))
        batch_op.drop_index(batch_op.f('ix_attachments_entity_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_colaborador'))

    op.drop_table('assets')
    # ### end Alembic commands ###
